version: "3"

services:
  web:
    build: .
    command: [ "jekyll", "serve", "-H", "0.0.0.0", "-l" ]
    ports:
      - 4000:4000
      - 35729:35729
    stdin_open: true
    tty: true
    volumes:
      - bundler-data:/usr/local/bundle
      - .:/app

volumes:
  bundler-data:
